server:
  port: 8082

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5434/user-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "?eU(@EK; V,iN<tdy*AS4TYd6k{^azD=PHe:Q*f?0[q3'$k[p<BvuUxbiB`'O:w"
  expirationMs: 3600000  # 1 saat