version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - example-net

  redis:
    image: redis:7-alpine
    container_name: gateway-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - example-net

  analyze-db:
    image: postgres:latest
    container_name: analyze-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: analyze-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - analyze-db-data:/var/lib/postgresql/data
    networks:
      - example-net

  git-db:
    image: postgres:latest
    container_name: git-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: git-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - git-db-data:/var/lib/postgresql/data
    networks:
      - example-net

  user-db:
    image: postgres:latest
    container_name: user-db
    restart: always
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.18
    container_name: context-neo4j
    ports:
      - 7474:7474 # Web UI
      - 7687:7687 # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - ./data:/data

  ngrok:
    image: ngrok/ngrok:latest
    container_name: devsync-ngrok
    restart: unless-stopped
    command: http host.docker.internal:8081
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

volumes:
  analyze-db-data:
  git-db-data:
  user-db-data:

networks:
  example-net:
    driver: bridge
