server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"

          routes:
            - id: analyze-service
              uri: http://localhost:8080
              predicates:
                - Path=/analyze/**
              filters:
                - RewritePath=/analyze/(?<segment>.*), /api/analyze/${segment}

            - id: git-service
              uri: http://localhost:8081
              predicates:
                - Path=/git/**
              filters:
                - RewritePath=/git/(?<segment>.*), /api/git/${segment}
