server:
  port: 8080

spring:
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"

      routes:
        - id: analyze-service
          uri: lb://analyze-service
          predicates:
            - Path=/analyze/**
          filters:
            - RewritePath=/analyze/(?<segment>.*), /api/analyze/${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: git-service
          uri: lb://git-service
          predicates:
            - Path=/git/**
          filters:
            - RewritePath=/git/(?<segment>.*), /api/git/${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/auth/${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

        - id: context-graph-service
          uri: lb://context-graph-service
          predicates:
            - Path=/context-graph/**
          filters:
            - RewritePath=/context-graph/(?<segment>.*), /api/context-graph/${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka